import type { Metadata } from "next";
import { inter, merriweather, playfair } from "@/components/ui/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.className}  antialiased`}
      >
        {children}
        
      </body>
    </html>
  );
}
